# Generated by Django 5.1.2 on 2024-10-15 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_articles_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2024, 10, 15, 13, 52, 41, 373073, tzinfo=datetime.timezone.utc), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
