# Generated by Django 5.1.2 on 2024-10-24 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_article_description_article_image_article_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='store/files/product_images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 9, 26, 37, 510678, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
